import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import { Spinner, Weather } from "../components";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState("");
  const [loading, setLoading] = useState(false);
  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = async () => {
    setLoading(true);
    try {
      const { data } = await axios.get(url);
      setWeather(data);
    } catch (e) {
      console.log({ msg: e });
    }
    setLoading(false);
  };

  console.log(weather);
  return (
    <div>
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />
      <Image
        src="https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=775&q=80"
        layout="fill"
        className="object-cover"
      />
      <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10">
        <form
          className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl"
          onSubmit={fetchWeather}
        >
          <div>
            <input
              className="bg-transparent border-none text-white focus:outline-none text-2xl"
              type={"text"}
              placeholder="search city"
            />
          </div>
          <button onClick={fetchWeather}>
            <BsSearch size={20}/>
          </button>
        </form>
      </div>
      {/* weather */}
      {weather.main && <Weather />}
    </div>
  );
}
